print(".............................................")
print("Tugas day 1 sisop kelas A")
print(".............................................")
print("NAMA : Yunita nur")
print("NPM  : 21083010107")
print(".............................................")
print("notes :")
print(".............................................")
print("halo dunia!")
print("ini adalah skrip bash pertamaku di Linux!")
print(".............................................")
